###GET ALL
GET http://localhost:3000/products

###GET AND SORT DESCENDING
GET http://localhost:3000/products?sortCol=name&sortOrder=desc


###GET AND SORT DESC AND SEARCH/FILTER
GET http://localhost:3000/products?q=ur&sortCol=name&sortOrder=desc